# Change these first
owner: JARVIS-discordbot # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Dashboard
    url: https://jarvisdiscordbot.net/
  - name: Bot
    url: $BOT_IP
  - name: electronenclave.com (My electronics site)
    url: https://electronenclave.com/





status-website:
  cname: status.jarvisdiscordbot.net
  logoUrl: https://github.com/JARVIS-discordbot/status/blob/master/images/jarvis.gif?raw=true
  name: J.A.R.V.I.S Status
  robotsText: "User-agent: * \n Disallow: /"




  introTitle: "J.A.R.VI.S Status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/JARVIS-discordbot/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

skipDeleteIssues: true

assignees:
  - BenCos17 





